services:
  app:
    build: 
      context: ./docker/php
    container_name: fincore_app
    restart: always
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - mysql
    networks:
      - fincore-network

  nginx:
    image: nginx:latest
    container_name: fincore_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - fincore-network

  mysql:
    image: mysql:8.0
    container_name: fincore_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fincore
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - fincore-network

  adminer:
    image: adminer:latest
    container_name: fincore_adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - fincore-network

  node: 
    image: node:22
    container_name: fincore_node
    restart: always
    working_dir: /var/www
    volumes:
      - .:/var/www
    command: bash -c "npm install && npm run dev"
    ports:
      - "5173:5173"
    networks:
      - fincore-network

  composer:
    build: 
      context: ./docker/php
    container_name: fincore_composer
    working_dir: /var/www
    volumes:
      - .:/var/www
    command: bash -c "composer install"
    entrypoint: ["composer"]
    networks:
      - fincore-network

networks:
  fincore-network:

volumes:
  mysql_data:
